name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    permissions:
      contents: read
    name: Test (Julia 1.12)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Set up Julia
        uses: julia-actions/setup-julia@4c0cb0fce8556fdb04a90347310e5db8b1f98fb9 # v2
        with:
          version: "1.12"

      - name: Cache Julia packages
        uses: julia-actions/cache@d10a6fd8f31b12404a54613ebad242900567f2b9 # v2

      - name: Run tests
        uses: julia-actions/julia-runtest@6e050c8013b833b1195105ff2fce9cd802f53271 # v1
